services:
  - type: web
    name: social-media-admin
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        value: post-images
      - key: CONTACT_EMAIL
        value: farrukhasif867@gmail.com
      - key: WHATSAPP_NUMBER
        value: +923074442888